// src/components/UiFriendRequest.tsx
import React, {useEffect, useState} from 'react';
import {useAuthContext} from "@/context/AppContext";
import {useRouter} from "next/navigation";

interface FriendRequestProps {
  hasFriendQuery: string[];
}

const FriendRequest: React.FC<FriendRequestProps> = ({ hasFriendQuery }) => {
  const {addFriend}: any = useAuthContext()
  const router = useRouter();

  const [isAccepted, setIsAccepted] = useState(false);

  function addFriendHandler() {
    addFriend(hasFriendQuery[0], hasFriendQuery[1]);
    setIsAccepted(true);
    router.push('/');
  }

  return (
    <>
      {!isAccepted && hasFriendQuery.length === 2 &&
        <div className='flex flex-col gap-4 bg-emerald-400 w-full text-white rounded-2xl p-4'>
          <p className='text-center'>
            Would you like
            <br/><strong>{hasFriendQuery[1]}</strong><br/>
            to join this list
          </p>
          <div className='flex items-center justify-center gap-6'>
            <button onClick={() => router.push('/')}
                    className='rounded p-2 font-bold flex justify-center border border-gray-300 text-white'>
              Ignore
            </button>
            <button onClick={() => addFriendHandler()}
                    className='rounded p-2 font-bold flex justify-center bg-white text-emerald-500 px-6'>
              Accept
            </button>
          </div>
        </div>
      }
    </>
  );
};

export default FriendRequest;

// src/components/UiFriendRequest.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { addFriend } from '$lib/store';
	import { derived } from 'svelte/store';
	import { isValidEmail } from '$lib/auth';

	const hasFriendQuery = derived(page, ($page) => {
		const search = $page.url.searchParams.get('friend');
		const urlQuery = search?.replace(/\?friend=/, '').split(';') ?? [];
		return urlQuery.length === 2 && isValidEmail(urlQuery[1]) ? urlQuery : [];
	});

	let isAccepted: boolean = false;

	function addFriendHandler(): void {
		if ($hasFriendQuery.length === 2) {
			addFriend($hasFriendQuery[0], $hasFriendQuery[1]);
			isAccepted = true;
			goto('/');
		}
	}
</script>

{#if !isAccepted && $hasFriendQuery.length === 2}
	<div class="flex w-full flex-col gap-4 rounded-2xl bg-emerald-400 p-4 text-white">
		<p class="text-center">
			Would you like
			<br />
			<strong>{$hasFriendQuery[1]}</strong>
			<br />
			to join this list
		</p>
		<div class="flex items-center justify-center gap-6">
			<button
				on:click={() => goto('/')}
				class="flex justify-center rounded border border-gray-300 p-2 font-bold text-white"
			>
				Ignore
			</button>
			<button
				on:click={addFriendHandler}
				class="flex justify-center rounded bg-white p-2 px-6 font-bold text-emerald-500"
			>
				Accept
			</button>
		</div>
	</div>
{/if}
