// src/components/UiItemInput.tsx
'use client'

import {useAuthContext} from "@/context/AppContext";
import {FormEvent, useState} from "react";
import SuggestList from "@/components/UiSuggests";

export default function UiItemInput() {
  const {addItem, listSuggest, loading}: any = useAuthContext();
  const [inputValue, setInputValue] = useState('');

  function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    onAddItem(inputValue);
  }

  function onAddItem(item: string) {
    addItem(item);
    setInputValue('');
  }

  return (
    <div className={`w-full relative ${loading ? 'pointer-events-none' : ''}`}>

      <form onSubmit={handleSubmit} className="flex gap-3 justify-center">
          <input
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            required
            name="item"
            placeholder="Strawberries"
            className="border rounded-2xl px-3 py-2 text-black shadow w-full md:w-72"
          />
        <button
          type="submit"
          className="green-gradient-bg text-white text-lg px-3 rounded-2xl border border-gray-200 shadow"
        >
          Add
        </button>
      </form>

      <SuggestList
        suggestsList={listSuggest}
        item={inputValue}
        onAddItem={onAddItem}
      />
    </div>
  );
}

// src/components/UiItemInput.svelte
<script lang="ts">
	import { addItem, listSuggest, loading } from '$lib/store'; // Replace with your store path
	import SuggestList from './UiSuggestList.svelte'; // Adjust the path as needed

	let inputValue = '';

	const onAddItem = (item: string) => {
		addItem(item);
		inputValue = '';
	};

	const handleSubmit = (event: Event) => {
		event.preventDefault();
		onAddItem(inputValue);
	};
</script>

<div class={`relative w-full ${$loading ? 'pointer-events-none' : ''}`}>
	<form on:submit|preventDefault={handleSubmit} class="flex justify-center gap-3">
		<input
			bind:value={inputValue}
			required
			name="item"
			placeholder="Strawberries"
			autocomplete="off"
			class="w-full rounded-2xl border px-3 py-2 text-black shadow md:w-72"
		/>
		<button
			type="submit"
			class="green-gradient-bg rounded-2xl border border-gray-200 px-6 text-lg text-white shadow-lg transition-all hover:opacity-90"
		>
			add
		</button>
	</form>

	<SuggestList suggestsList={$listSuggest} item={inputValue} {onAddItem} />
</div>
