// src/components/UiList.tsx
'use client'

import {useAuthContext} from "@/context/AppContext";
import React from "react";
import Image from "next/image";
import CloseIcon from "@/assets/close.svg";

export default function UiList() {
  const {loadingList, list, removeItem, loading}: any = useAuthContext()
  return (
    <div className="w-full md:w-[420px]">
      {loadingList && <Image src='/loading.svg' alt='loading' width={90} height={90} className='mx-auto'/>}
      <div className="">
        <ul className='grid gap-3'>
          {list && Object.keys(list).reverse().map((item: any) => {
            return (
              <li key={item} className='flex items-center gap-5 border border pl-4 p-2 rounded-xl justify-between'>
                <p>{list[item]}</p>
                <button onClick={() => removeItem(item, 'list')}>
                  <CloseIcon className='h-6 w-6 text-red-300'/>
                </button>
              </li>
            )
          })}
        </ul>
        { !list && !loadingList && <p className='text-center'>Your list is empty.</p>}
      </div>
    </div>
  );
}

// src/components/UiList.svelte
<script lang="ts">
	import { loadingList, list, removeItem } from '$lib/store'; // Adjust the path as needed
	import IconClose from '../components/icons/icon-close.svelte'; // Adjust path to your CloseIcon SVG
</script>

<div class="w-full md:w-[420px]">
	{#if $loadingList}
		<img src="/loading.svg" alt="loading" width="90" height="90" class="mx-auto" />
	{/if}

	<div>
		<ul class="grid gap-3">
			{#if $list}
				{#each Object.keys($list).reverse() as item}
					<li class="flex items-center justify-between gap-5 rounded-xl border p-2 pl-4">
						<p>{$list[item]}</p>
						<button on:click={() => removeItem(item, 'list')}>
							<IconClose />
						</button>
					</li>
				{/each}
			{:else if !$loadingList}
				<p class="text-center">Your list is empty.</p>
			{/if}
		</ul>
	</div>
</div>
