// src/components/UiSignUp.svelte
<script lang="ts">
	import { signUp } from '$lib/auth';
	import IconLoading from './icons/icon-loading-circle.svelte';

	let email: string = '';
	let password: string = '';
	let errors: string | null = null;
	let loading: boolean = false;

	async function handleForm(event: Event): Promise<void> {
		event.preventDefault();
		loading = true;

		try {
			const { error }: any = await signUp(email, password);
			if (error) {
				errors = error.code.replace(/auth\//, '').replace(/-/g, ' ');
			}
		} catch (error: any) {
			errors = error.code.replace(/auth\//, '').replace(/-/g, ' ');
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-w-[300px]">
	<p class="text-center text-2xl">Register to create a list</p>
	<form on:submit|preventDefault={handleForm} class="mt-6 flex flex-col gap-4">
		<div class="flex flex-col gap-3">
			<label for="email">
				<p>Email</p>
				<input
					bind:value={email}
					required
					type="email"
					name="email"
					id="email"
					placeholder="my-email@gmail.com"
					class="w-full rounded border p-3 text-black"
					autocomplete="off"
				/>
			</label>

			<label for="new-password">
				<p>Password</p>
				<input
					bind:value={password}
					required
					type="password"
					name="password"
					id="new-password"
					placeholder="password"
					class="w-full rounded border p-3 text-black"
					autocomplete="new-password"
				/>
			</label>
		</div>

		<!-- Submit Button -->
		<button
			type="submit"
			class="green-gradient-bg flex justify-center rounded p-2 font-bold text-white"
		>
			{#if loading}
				<IconLoading classes="w-6" />
			{:else}
				Sign up
			{/if}
		</button>
	</form>

	<!-- Error Display -->
	<div class="mt-6 w-full text-center text-sm">
		<p class="capitalize text-red-400">{errors}</p>
	</div>
</div>

<style>
	/* Additional styles can go here, or use Tailwind CSS */
</style>

// src/components/UiSignUp.tsx
'use client'

import {useState} from "react";
import {signUp} from "@/firebase/auth";
import IconLoading from '@/assets/loading-circle.svg'

export default function UiSignUp() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [errors, setErrors] = useState(null)
  const [loading, setLoading] = useState(false)


  const handleForm = async (event: any) => {
    event.preventDefault()
    setLoading(true)
    const {error}: any = await signUp(email, password)
    if (error) {
      setErrors(error.code.replace(/auth\//, '').replace(/-/g, ' '))
    }
    setLoading(false)
  }

  return (
    <div className='min-w-[300px]'>
      <p className='text-center text-2xl'>
        Create list
      </p>
      <form onSubmit={handleForm} className='flex flex-col gap-4 mt-6'>
        <div className='flex flex-col gap-3'>
          <label htmlFor="email" className=''>
            <p>Email</p>
            <input onChange={(e) => setEmail(e.target.value)} required type='email' name="email" id="email"
                   placeholder="my-email@gmail.com" className='text-black border p-3 rounded w-full'/>
          </label>
          <label htmlFor="new-password" className=''>
            <p>Password</p>
            <input onChange={(e) => setPassword(e.target.value)} required type="password" name="password"
                   id="new-password" placeholder="password" className='text-black border p-3 rounded w-full'/>
          </label>
        </div>
        <button type="submit" className='green-gradient-bg rounded p-2 text-white font-bold flex justify-center'>
          {loading ? <IconLoading className='w-6'/> : 'Sign up'}
        </button>
      </form>
      <div className='mt-6 w-full text-center text-sm'>
        <p className='text-red-400'>{errors}</p>
      </div>
    </div>);
}
