// src/routes/signup/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { user } from '$lib/store';
	import UiSignUp from '@components/UiSignUp.svelte';

	user.subscribe((value) => {
		if (value) {
			goto('/');
		}
	});
</script>

<section class="flex justify-center gap-4 lg:gap-10">
	<UiSignUp />
</section>

// src/app/signup/page.tsx
'use client'

import React, {useEffect} from "react";
import UiSignUp from "@/components/UiSignUp";
import {useAuthContext} from "@/context/AppContext";
import {useRouter} from 'next/navigation';

export default function Signup() {
  const {user}: any = useAuthContext();
  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push('/');
    }
  }, [router, user]);

  return (
    <section
      className='flex justify-center gap-4 lg:gap-10'>
      <UiSignUp/>
    </section>
  )
}
